function [ identifier ] = ppGetUniqueDicomIdentifier(filePath)
% Creates a unique dicom identifier from the dicom header

identifier       = '';

%% Error if DICOM file is missing
if exist(filePath) < 1
  throw(MException('PPS:GetUniqueDicomIdentifier','Dicom does not exist(%s)', filePath));
  return
end

%% Obtain dicom header
[unused, header] = ppFileinfo(filePath);

%% Assemble unique id
identifier       = sprintf( ...
 '%s#%s#%d#%d#%s#%s',...
 header.PatientName.FamilyName, ...
 header.PatientName.GivenName, ...
 header.SeriesNumber, ...
 header.AcquisitionNumber, ...
 header.ProtocolName, ...
 header.AcquisitionDate ...
);